#!/bin/bash
xhost +local:docker
docker run -d -p 3000:3000 -e NODE_ENV=development -e PORT=3000 -e DISPLAY="${DISPLAY:-:0}" -h katana -v  bookflow_data:/app/data -v /tmp/.X11-unix:/tmp/.X11-unix bookflow-reading-journal:latest
